### PR TITLE
Updated to support Surface Pen on Surface devices.

### PR DESCRIPTION
**Pull request by ZZZXXX0110**
Added the line to define Surface Pen device on Surface devices.
Added the line to fetch device ID for Surface Pen device.
Added the line that command coordinate transformation for Surface Pen on Surface devices.

### CODE REVIEW

**Comment by dos1** [comment]
Is the rotation property really called "Pen Pen" on Pen Pen devices? :thinking:

**Comment by ZZZXXX0110** [comment]
Oh! Well, "xinput list-props `xinput list --id-only "Pen Pen"`" doesn't give any result, but "xinput list-props 19" (with 19 being the device id of it on my current session) gives these output:

Device 'ipts 045E:001F Pen Pen (0)':
        Device Enabled (148):   1
        Coordinate Transformation Matrix (150): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        Device Node (273):      "/dev/input/event8"
        Device Product ID (274):        1118, 31
        libinput Tablet Tool Pressurecurve (663):       0.000000, 0.000000, 0.000000, 0.000000, 1.000000, 1.000000, 1.000000, 1.000000

**Comment by dos1** [comment]
Looking from this output, seems like setting Coordinate Transformation Matrix should be enough.

So, looks like the line 63/66 is the only one that actually needs changing there (replacing `IS_TOUCH` with something like `IS_GENERIC` might be sensible then though).

**Comment by ZZZXXX0110** [comment]
However, with Coordinate Transformation Matrix alone only handled my touchscreen, and did not actually transform the coordinate for my Pen.

**Comment by ZZZXXX0110** [comment]
By the way, on Surface device, the Pen and the touchscreen uses exactly the same hardware, but are registered as different input devices. This is why the same coordinate transformation matrix works for both touchscreen and pen, but the pen need to be recognized as a separate device.

**Comment by dos1** [comment]
Separate device - yes, but you've also added a separate property into the code, which as far as I can tell from the output you pasted, doesn't actually exist ;)

**Comment by ZZZXXX0110** [comment]
I see, you have a good point! ;)

By property you are referring to like "GENERIC_PROP" right? What do they do exactly? That's one thing I didn't entirely figure out in your code lol

**Comment by dos1** [comment]
Right. This is the property name to change. Your device exports following properties: "Device Enabled", "Coordinate Transformation Matrix", "Device Node", "Device Product ID", "libinput Tablet Tool Pressurecurve".

Generally you want to set "Coordinate Transformation Matrix", however, apparently some devices like Wacom tablets might need something else.

**Comment by ZZZXXX0110** [comment]
I think my question was how this property is used by the rest of the code? I thought it as simply a variable that is used later on as I see "$GENERIC_PROP$" down the line, but what exactly is this variable used for? What reads the information it contains?

I'm very new to coding in general, so I'm really curious how you designed this script.

**Comment by dos1** [comment]
This part of code was actually contributed, but it's not that hard to understand :)

Basically, the scripts checks whether your device contains a property called "Coordinate Transformation Matrix" (`$GENERIC_PROP`) or "Wacom Rotation" (`$WACOM_PROP`) and then sets one accordingly. As far as I can tell, you shouldn't need to change anything there - just adding a string to name check in `IS_TOUCH` should be enough.

**Comment by ZZZXXX0110** [comment]
Ohhhhhh! That makes sense now! :D

**Comment by dos1** [comment]
@ZZZXXX0110  Could you take a look at #10?

**Comment by SiKreuz** [comment]
@dos1 @ZZZXXX0110 #11 now, sorry!

**Comment by dos1** [comment]
I'm closing this one as I've merged #11. Feel free to yell if something still needs to be done there :)

**Pull request closed without merging**
